version: '3.8'
services:
  lab:
    build: .
    ports:
      - "8888:8888"
    
    volumes:
      - .:/home/jovyan/project
    
    env_file:
      - .env

    working_dir: /home/jovyan/project/workspace
    container_name: jupyter-lab-pro-project

    command: >
      jupyter lab
      --notebook-dir=/home/jovyan/project/workspace
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/home/jovyan/project
    ports:
      - "8000:8000"
    env_file:
      - .env
    container_name: fastapi-backend-service
  frontend:
    build: .
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/home/jovyan/project
    ports:
      - "8501:8501"
    container_name: streamlit-frontend-service
    depends_on:
      - backend